import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css';
import t_en from '../translations/en.json';
import t_pt from '../translations/pt.json';
import {useContext, useMemo} from "react";
import SelectLanguage from "../components/selectLanguage";
import {LanguageContext} from "./_app";

const TRANSLATIONS = {
  en: t_en,
  pt: t_pt
}

export default function Home(props) {

  const {language} = useContext(LanguageContext);

  const t = useMemo(() => TRANSLATIONS[language || "en"], [language]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/public/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <SelectLanguage/>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>{t["label_1"]}</h2>
            <p>{t["label_2"]}</p>
          </div>

          <div className={styles.card}>
            <h2>{t["label_1"]}</h2>
            <p>{t["label_2"]}</p>
          </div>

          <div className={styles.card}>
            <h2>{t["label_1"]}</h2>
            <p>{t["label_2"]}</p>
          </div>

          <div className={styles.card}>
            <h2>{t["label_1"]};</h2>
            <p>{t["label_2"]}</p>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>
    </div>
  )
}

